import Link from "next/link";
import { ArrowRight, CheckCircle2, Clock3 } from "lucide-react";
import { Footer } from "@/components/Footer";
import { SiteHeader } from "@/components/SiteHeader";
import { chapters, layers, pick, validLocale } from "@/lib/content";

export default async function TimelinePage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: raw } = await params; const locale = validLocale(raw);
  const total = chapters.reduce((sum, item) => sum + item.minutes, 0);
  return <div className="page-shell"><SiteHeader locale={locale} /><main className="timeline-page section-pad"><section className="subpage-title"><div className="section-kicker">ZERO TO SOURCE READER</div><h1>{locale === "zh" ? `${Math.round(total / 60)} 小时，不是速览：是一条完整认知坡道` : `${Math.round(total / 60)} hours—not a skim, but a complete learning ramp`}</h1><p>{locale === "zh" ? "六次学习会话从全局直觉逐步推进到扩展交付。每层都明确前置问题、学习结果与通向下一层的原因。" : "Six sessions move from mental model to shipped extensions. Each names its prerequisite, outcome, and reason for the next layer."}</p></section><div className="timeline">{layers.map((layer, layerIndex) => { const items = chapters.filter(chapter => chapter.layer === layer.id); const minutes = items.reduce((sum, item) => sum + item.minutes, 0); return <section className={`timeline-stop tone-${layer.color}`} key={layer.id}><div className="timeline-marker"><span>{layer.no}</span></div><div className="timeline-content"><div className="timeline-head"><div><small>SESSION {layerIndex + 1}</small><h2>{pick(layer.title, locale)}</h2><p>{pick(layer.desc, locale)}</p></div><span><Clock3 />≈ {minutes} min</span></div><div className="timeline-outcome"><CheckCircle2 /><div><small>{locale === "zh" ? "完成这一层，你将能够" : "After this layer, you can"}</small><b>{pick(layer.outcome, locale)}</b></div></div><div className="timeline-chapters">{items.map(chapter => <Link key={chapter.slug} href={`/${locale}/chapter/${chapter.slug}`}><code>{chapter.slug.split("-")[0].toUpperCase()}</code><span><b>{pick(chapter.title, locale)}</b><small>{pick(chapter.question, locale)}</small></span><em>{chapter.minutes}m</em><ArrowRight /></Link>)}</div></div></section>; })}</div></main><Footer locale={locale} /></div>;
}
